changesetIgnorePatterns:
  - "**/*.spec.{js,ts,tsx}"

npmAuthToken: "${NPM_AUTH_TOKEN-emptytoken}"

packageExtensions:
  "@fluentui/font-icons-mdl2@*":
    peerDependencies:
      react: "*"
  "@fluentui/foundation-legacy@*":
    peerDependencies:
      react: "*"
  "@fluentui/react-focus@*":
    peerDependencies:
      react: "*"
  "@fluentui/react@*":
    peerDependencies:
      "@types/prop-types": "*"
      prop-types: "*"
      react: "*"
  "@fluentui/style-utilities@*":
    peerDependencies:
      react: "*"
  "@fluentui/theme@*":
    peerDependencies:
      react: "*"
  "@fluentui/utilities@*":
    peerDependencies:
      react: "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
  "@storybook/addon-knobs@*":
    peerDependencies:
      "@storybook/client-api": "*"
  "@testing-library/react@*":
    dependencies:
      "@types/pretty-format": ^24.3.0
      pretty-format: 26.5.2
  "@thematic/d3@*":
    peerDependencies:
      "@types/d3-axis": "*"
  "@thematic/fluent@*":
    peerDependencies:
      "@fluentui/font-icons-mdl2": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
