changesetIgnorePatterns:
  - "**/*.spec.{js,ts,tsx}"

npmAuthToken: "${NPM_AUTH_TOKEN-emptytoken}"

packageExtensions:
  "@fluentui/font-icons-mdl2@*":
    peerDependencies:
      react: "*"  
  "@fluentui/style-utilities@*":
    peerDependencies:
      react: "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
      "webpack": "*"
    peerDependenciesMeta:
      "@babel/core":
        optional: true
      "webpack":
        optional: true
  "@storybook/addon-essentials@*":
    peerDependencies:
      "react": "*"
  "@storybook/telemetry@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/instrumenter@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/docs-tools@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/testing-library@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@storybook/mdx1-csf@*":
    peerDependencies:
      "@babel/core": "*"
  "@devtools-ds/themes@*":
    peerDependencies:
      "react-dom": "*"
  "@devtools-ds/tree@*":
    peerDependencies:
      "react-dom": "*"
  "@devtools-ds/object-inspector@*":
    peerDependencies:
      "react-dom": "*"
  "@testing-library/react@*":
    dependencies:
      "@types/pretty-format": ^24.3.0
      pretty-format: 26.5.2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
